name = "htmlark-remote"
main = "src/index.ts"
compatibility_date = "2026-09-03"
account_id = "c7aabbf4ff9f13a34351cb7cf2d015d1"

[vars]
PUBLIC_ORIGIN = "https://a.htmlark.com"

[[r2_buckets]]
binding = "ARTIFACTS"
bucket_name = "htmlark-artifacts"

[[d1_databases]]
binding = "DB"
database_name = "htmlark-index"
database_id = "78f23cac-46bf-45cf-ad5c-64c8215ce76c"

[[routes]]
pattern = "a.htmlark.com"
custom_domain = true
